title: TRANSMIXR Documentation
description: An overview of the technical results for the TRANSMIXR project.
theme: just-the-docs

url: https://transmixr.github.io

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://transmixr.github.io
